### ISSUE TITLE
data folder

### ISSUE THREAD

**Issue by CirceJie** [csiro-icvg/Diff3DHPE#2]
hi! 
first of all, thank you for your working. Did you forget to make the data folder public？ I got a error message cause I cannot find some load_noisy_data.py file
![20240513002456](https://github.com/csiro-icvg/Diff3DHPE/assets/79498805/03d07853-911e-4f2b-ae8d-f48c00e322ff)

**Comment by socoolzjm** [comment]
Thank you for raising the issue. It was my mistake. The data directory is uploaded now.
